name = "vany"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# KV Namespaces
[[kv_namespaces]]
binding = "SAFEBOX"
id = "4f5c4f3d5e784fe99fefec2ce5007ce8"
preview_id = "d75c9bd6ffc0437685ae7710c01453f0"

# Routes - TUI serving and protocol info pages
routes = [
  { pattern = "start.vany.sh", custom_domain = true },
  { pattern = "www.vany.sh/*", zone_name = "vany.sh" },
  { pattern = "mtp.vany.sh", custom_domain = true },
  { pattern = "reality.vany.sh", custom_domain = true },
  { pattern = "wg.vany.sh", custom_domain = true },
  { pattern = "vray.vany.sh", custom_domain = true },
  { pattern = "ws.vany.sh", custom_domain = true },
  { pattern = "dnstt.vany.sh", custom_domain = true },
  { pattern = "conduit.vany.sh", custom_domain = true },
  { pattern = "vany.sh", custom_domain = true }
]
